apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: colour
  namespace: nginx-ingress
spec:
  host: colour.example.com
  policies:
    - name: common-sec-policy
      namespace: security
  routes:
    - path: /blue
      route: blue/blue-vsr
    - path: /green
      route: green/green-vsr
