apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: colour
  namespace: nginx-ingress
spec:
  host: colour.example.com
  routes:
    - path: /
      action:
        return:
          code: 200
          type: text/plain
          body: "Virtual Server is up.\n"
    - path: /blue
      route: blue/blue-vsr
    - path: /green
      route: green/green-vsr
