apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: green-vsr
  namespace: green
spec:
  host: colour.example.com
  upstreams:
    - name: green-svc
      service: nginx-green
      port: 8080
  subroutes:
    - path: /green
      action:
        proxy:
          upstream: green-svc
          rewritePath: /
