apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: nic-tls-passthrough
  namespace: nic-demo-tls-passthrough
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: tls-passthrough.nic-demo.com
  upstreams:
    - name: nginx-tls
      service: nginx-tls
      port: 443
  action:
    pass: nginx-tls
