apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: httpbin
  namespace: nic-demo-waf
spec:
  host: httpbin.nic-demo-waf.com
  upstreams:
    - name: httpbin-svc
      service: httpbin
      port: 8080
  routes:
    - path: /
      action:
        pass: httpbin-svc
