apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: block-bot-allow-curl
  namespace: nic-demo-waf
spec:
  policy:
    applicationLanguage: utf-8
    enforcementMode: blocking
    name: block-bot-allow-curl
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    bot-defense:
      settings:
        isEnabled: true
      mitigations:
        classes:
          - name: trusted-bot
            action: ignore
          - name: untrusted-bot
            action: block
          - name: malicious-bot
            action: block
        signatures:
          - action: alarm
            name: curl
---
apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: logconf
  namespace: nic-demo-waf
spec:
  content:
    format: default
    max_message_size: 64k
    max_request_size: any
  filter:
    request_type: illegal
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
  namespace: nic-demo-waf
spec:
  waf:
    apPolicy: block-bot-allow-curl
    enable: true
    securityLogs:
      - apLogConf: logconf
        enable: true
        logDest: stderr
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: httpbin
  namespace: nic-demo-waf
spec:
  host: httpbin.nic-demo-waf.com
  policies:
    - name: waf-policy
  upstreams:
    - name: httpbin-svc
      service: httpbin
      port: 8080
  routes:
    - path: /
      action:
        pass: httpbin-svc
