apiVersion: v1
kind: Namespace
metadata:
  name: nic-demo-jwt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: nic-demo-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: nic-demo-jwt
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: jwt
  namespace: nic-demo-jwt
spec:
  jwt:
    realm: default
    secret: my-jwks
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: httpbin
  namespace: nic-demo-jwt
spec:
  host: httpbin.nic-demo-jwt.com
  upstreams:
    - name: httpbin-svc
      service: httpbin
      port: 8080
  routes:
    - path: /
      action:
        pass: httpbin-svc
