apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: httpbin
  namespace: nic-demo-jwt
spec:
  host: httpbin.nic-demo-jwt.com
  policies:
    - name: jwt
  server-snippets: |
    set $http_role $jwt_claim_role;
  upstreams:
    - name: httpbin-svc
      service: httpbin
      port: 8080
  routes:
    - path: /
      action:
        proxy:
          upstream: httpbin-svc
          requestHeaders:
            set:
              - name: Jwt-Claim-Role
                value: ${jwt_claim_role}
              - name: Jwt-Claim-Name
                value: ${jwt_claim_name}
    - path: /anything
      matches:
        - conditions:
            - variable: $request_method
              value: POST
            - header: role
              value: "admin"
          action:
            pass: httpbin-svc
      action:
        return:
          code: 401
          type: text/plain
          body: "401 Unauthorized\n"
