apiVersion: v1
kind: Namespace
metadata:
  name: nic-demo-dos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: nic-demo-dos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: httpbin
          resources:
            requests:
              cpu: "5m"
            limits:
              cpu: "15m"
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: nic-demo-dos
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: baseline-script
  namespace: nic-demo-dos
data:
  baseline.sh: |
    #!/usr/bin/env sh

    set -e
    CURL_OUTPUT_FORMAT='total_time: %{time_total}s, exit_code: %{exitcode}, err_msg: "%{errormsg}", http_resp_code: %{response_code}\n'

    while true; do
      CURL_OUTPUT=$(curl -o /dev/null -s -w "$CURL_OUTPUT_FORMAT" httpbin.nic-demo-dos.com/bytes/$RANDOM)

      echo "timestamp: $(date '+%Y/%m/%d %H:%M:%S'), $CURL_OUTPUT"

      sleep 0.5
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baseline-client
  name: baseline-client
  namespace: nic-demo-dos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseline-client
  template:
    metadata:
      labels:
        app: baseline-client
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: baseline-script
            items:
              - key: baseline.sh
                path: baseline.sh
      containers:
        - image: curlimages/curl
          name: curl
          command:
            - sh
          args:
            - /home/curl_user/baseline.sh
          volumeMounts:
            - name: config-volume
              mountPath: /home/curl_user
      hostAliases:
        - hostnames:
            - httpbin.nic-demo-dos.com
          ip: 192.168.255.100
