apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-green
  namespace: green
data:
  index.html: |
    green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-green
  name: nginx-green
  namespace: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          volumeMounts:
            - name: nginx-conf
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-green
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-green
  name: nginx-green
  namespace: green
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-green
  type: NodePort
