apiVersion: v1
kind: Namespace
metadata:
  name: blue
  labels:
    name: blue
---
apiVersion: v1
kind: Namespace
metadata:
  name: green
  labels:
    name: green
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
